config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :projects do
    resources :tasks do
      collection do
        patch :sort
      end
      member do
        patch :complete
        patch :dedline
      end
    end
  end
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  include RailsSortable::Model
  set_sortable :sort
  belongs_to :project

  def completed?
    !completed_at.blank?
  end

  def check_deadline
    self.errors.add('base', 'Deadline is expired') if self.expired?
  end

  def expired?
    self.deadline < Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    if user_signed_in?
      @projects = Project.where(:user_id => current_user.id)
    end
  end

  def show
    @project = Project.find(params[:id])
    @tasks = @project.tasks.order(:sort)
  end

  def new
    @project = current_user.projects.build
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = current_user.projects.build(project_params)

    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to projects_path
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, except: [:new, :create]

  def show
    @task = @project.tasks.find(params[:id])
    @project.tasks.last.move_higher
  end

  def new
    @task = @project.tasks.build
  end

  def edit
    @task = @project.tasks.find(params[:id])
  end

  def create
    @task = @project.tasks.build(task_params)
    if @task.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def update
    @task = @project.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    if @task.destroy
      flash[:success] = "Task was deleted"
    else
      flash[:error] = "Task couldn't deleted"
    end
    redirect_to @project
  end

  def complete
    @task.update_attribute(:completed_at, Time.now)
    redirect_to @project
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:task_description, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_static_pages.html.erb
<div class="jumbotron">
  <h1>Task Manager</h1>
  <p> If you don't have account</p>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
  <p>Or</p>
  <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">

        <div class="navbar-header">
          <%= link_to "TaskManager", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav">          
          <% if current_user.present? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>

        <% if user_signed_in? %>
          <%= link_to "New Project", new_project_path, class: "navbar-text navbar-link navbar-right" %>
        <% end %>

      </div>
    </nav>

    <div class="container">
     <%= render "layouts/alerts" %>
     <%= yield %>
   </div>

  </body>
</html>

app/views/projects/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Edit project</h1>

  <%= simple_form_for @project do |p| %>
    <%= p.input :title %>
    <%= p.input :description %>
    <%= p.button :submit %>
  <% end %>


  <%= link_to "Back", projects_path %>
</div>

app/views/projects/index.html.erb
<% if user_signed_in? %>

  <div class="col-md-6 col-md-offset-3">

    <div class="row item">

      <% @projects.each do |project| %>

        <div class="col-md-8">
          <h2><%= link_to project.title, project %></h2>
          <p><%= project.description %></p>
        </div>

        <div class="col-md-2">
          <p><%= link_to edit_project_path(project) do %></p>
            <i class="fa fa-lg fa-edit"></i>
          <% end %>
        </div>

        <div class="col-md-2">
          <p><%= link_to new_project_task_path(project) do %></p>
            <i class="fa fa-lg fa-tasks"></i>
          <% end %>
        </div>

        <div class="col-md-2">
          <p><%= link_to project, method: :delete, data: { confirm: "Are you sure?" } do %></p>
            <i class="fa fa-lg fa-trash"></i>
          <% end %>
        </div>

      <% end %>

    </div>

  </div>

<% else %>

    <%= render "layouts/static_pages" %>

<% end %>

app/views/projects/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Create new project</h1>

  <%= simple_form_for @project do |p| %>
    <%= p.input :title %>
    <%= p.input :description %>
    <%= p.button :submit %>
  <% end %>

  <%= link_to "Back", projects_path %>
</div>

app/views/projects/show.html.erb
<div class="col-md-6 col-md-offset-3">
  <p>
    <strong>Title</strong>
    <%= @project.title %>
  </p>

  <p>
    <strong>Description</strong>
    <%= @project.description %>
  </p>

  <div class="sortable">
    <% @tasks.each_with_sortable_id do |task, sortable_id| %>
     <%= render "tasks/task", task: task, sortable_id: sortable_id %>
    <% end %>
  </div>
  <%= render "tasks/form" %>


  <%= link_to "Edit", edit_project_path(@project) %>
  <%= link_to "Back", projects_path %>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for( [@project, @project.tasks.build] ) do |f| %>
  <%= f.input :task_description %>
  <%= f.input :deadline %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/_task.html.erb
<% if task.completed? %>

  <div id="<%= task.sortable_id %>" class="row item list-group">

    <div class="col-md-8 list-group-item">
      <p style="opacity: 0.5;"><strike><%= task.task_description %></strike></p>
      <p style="opacity: 0.5;"><%= task.deadline %></p>
    </div>

    <div class="col-md-2">
      <p><%= link_to complete_project_task_path(@project, task.id), method: :patch do %></p>
        <i class="fa fa-lg fa-check"></i>
      <% end %>
    </div>

    <div class="col-md-2">
      <p><%= link_to edit_project_task_path(@project, task.id) do %></p>
        <i class="fa fa-lg fa-edit"></i>
      <% end %>
    </div>

    <div class="col-md-2">
      <p><%= link_to project_task_path(@project, task.id), method: :delete, data: { confirm: "Are you sure?"} do %></p>
        <i class="fa fa-lg fa-trash"></i>
      <% end %>
    </div>

  </div>

<% else %>

  <div id="<%= task.sortable_id %>" class="row item list-group" >

    <div class="list-group-item col-md-8">
      <h3><%= task.task_description %></h3>

      <% if task.expired? %>
        <p><%= "Deadline expired" %></p>
      <% else %>
        <%= task.deadline %>
      <% end %>
    </div>

    <div class="col-md-2">
      <p><%= link_to complete_project_task_path(@project, task.id), method: :patch do %></p>
        <i class="fa fa-lg fa-check"></i>
      <% end %>
    </div>

    <div class="col-md-2">
      <p><%= link_to edit_project_task_path(@project, task) do %></p>
        <i class="fa fa-lg fa-edit"></i>
      <% end %>
    </div>

    <div class="col-md-2">
      <p><%= link_to project_task_path(@project, task.id), method: :delete, data: { confirm: "Are you sure?"} do %></p>
        <i class="fa fa-lg fa-trash"></i>
      <% end %>
    </div>

  </div>

<% end %>

app/views/tasks/destroy.js.erb
$('.delete').bind('ajax:success', function() {
  $(this).closest('p').fadeOut();
});

app/views/tasks/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= simple_form_for([@project, @task]) do |f| %>
    <%= f.input :task_description %>
    <%= f.input :deadline %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<%= simple_form_for( [@project, @project.tasks.build] ) do |f| %>
  <%= f.input :task_description %>
  <%= f.input :deadline %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/show.html.erb
<%= simple_form_for( [@project, @project.tasks.build] ) do |f| %>
  <%= f.input :task_description %>
  <%= f.input :deadline %>
  <%= f.button :submit %>
<% end %>